project:
  type: website

website:
  title: "What Works in Remote Math and Science Education"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - href: find_evidence.qmd
        text: Find What Works
      - href: aboutus.qmd
        text: About Us

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

