project:
  type: website

website:
  title: "What Works in Remote Math and Science Education"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - href: find_evidence.qmd
        text: Find What Works
      - href: aboutus.qmd
        text: About Us

format:
  html:
    theme:
      - cosmo
      - brand
    css: 
      - styles.css  # your custom site-wide styles
    toc: true
    include-in-header:
      - text: |
          <script src="https://cdnjs.cloudflare.com/ajax/libs/list.js/2.3.1/list.min.js"></script>

